version: '3'
services:
#mssql docker
  eoftamoloski-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
        - 1433
    networks:
      - eoftamoloskinet2022

  eoftamoloski-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:DefaultConnection=Server=eoftamoloski-sql,1433;Database=eOftamoloskiVjezbe;User=sa;Password=QWElkj132!;ConnectRetryCount=0
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5192:5192
    networks:
      - eoftamoloskinet2022
    links:
      - eoftamoloski-sql
    depends_on:
      - eoftamoloski-sql
      
networks:
  eoftamoloskinet2022:
    driver: bridge      